AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kafka_event_consumer_and_producer_functions

  Sample SAM Template for MSK consumer and AVRO producer with IAM auth

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  # SQS Queue to use as Dead Letter Queue for the MSK event source mapping
  ConsumerDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days (maximum retention period)
      VisibilityTimeout: 300  # 5 minutes
      Tags:
        - Key: Purpose
          Value: MSKConsumerDLQ

  LambdaMSKConsumerJavaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: kafka_event_consumer_function
      Handler: com.amazonaws.services.lambda.samples.events.kafka.AvroKafkaHandler::handleRequest
      Runtime: java25
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
          POWERTOOLS_LOG_LEVEL: TRACE
          POWERTOOLS_SERVICE_NAME: kafka_consumer
      Policies:
      - Statement:
        - Sid: KafkaClusterPermissionsPolicy
          Effect: Allow
          Action:
          - kafka-cluster:Connect
          - kafka-cluster:DescribeGroup
          - kafka-cluster:DescribeCluster
          - kafka-cluster:AlterCluster
          - kafka-cluster:AlterClusterDynamicConfiguration
          - kafka-cluster:WriteDataIdempotently
          - kafka-cluster:AlterGroup
          - kafka-cluster:DescribeTopic
          - kafka-cluster:ReadData
          - kafka-cluster:DescribeClusterDynamicConfiguration
          
        - Sid: KafkaPermissionsPolicy
          Effect: Allow
          Action:
          - kafka:DescribeClusterV2
          - kafka:GetBootstrapBrokers
          Resource: '*'
          
        - Sid: EC2PermissionsPolicy
          Effect: Allow
          Action:
          - ec2:DescribeSecurityGroups
          - ec2:DescribeSubnets
          - ec2:DescribeVpcs
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DeleteNetworkInterface
          Resource: '*'
          
        - Sid: GlueSchemaRegistryPermissionsPolicy
          Effect: Allow
          Action:
          - glue:GetSchemaByDefinition
          - glue:GetSchemaVersion
          - glue:GetRegistry
          - glue:ListSchemas
          - glue:ListSchemaVersions
          - glue:RegisterSchemaVersion
          - glue:PutSchemaVersionMetadata
          - glue:GetSchemaVersionsDiff
          - glue:QuerySchemaVersionMetadata
          Resource: '*'
          
        - Sid: SQSPermissionsPolicy
          Effect: Allow
          Action:
          - sqs:SendMessage
          Resource: !GetAtt ConsumerDLQ.Arn
      - VPCAccessPolicy: {}

  LambdaKafkaProducerJavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kafka_event_producer_function
      Handler: com.amazonaws.services.lambda.samples.events.kafka.AvroProducerHandler::handleRequest
      Runtime: java25
      Timeout: 300
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          BOOTSTRAP_SERVERS: !Ref BootstrapServers
          KAFKA_TOPIC: !Ref KafkaTopic
          REGISTRY_NAME: !Ref GlueSchemaRegistryName
          CONTACT_SCHEMA_NAME: !Ref ContactSchemaName
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Policies:
      - Statement:
        - Sid: KafkaClusterPermissionsPolicy
          Effect: Allow
          Action:
          - kafka-cluster:Connect
          - kafka-cluster:DescribeCluster
          - kafka-cluster:WriteData
          - kafka-cluster:DescribeTopic
          Resource: 
          
        - Sid: KafkaPermissionsPolicy
          Effect: Allow
          Action:
          - kafka:DescribeClusterV2
          - kafka:GetBootstrapBrokers
          Resource: '*'
          
        - Sid: EC2PermissionsPolicy
          Effect: Allow
          Action:
          - ec2:DescribeSecurityGroups
          - ec2:DescribeSubnets
          - ec2:DescribeVpcs
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DeleteNetworkInterface
          Resource: '*'
          
        - Sid: GlueSchemaRegistryPermissionsPolicy
          Effect: Allow
          Action:
          - glue:GetSchemaByDefinition
          - glue:GetSchemaVersion
          - glue:GetRegistry
          - glue:ListSchemas
          - glue:ListSchemaVersions
          - glue:GetSchemaVersionsDiff
          - glue:QuerySchemaVersionMetadata
          - glue:RegisterSchemaVersion
          - glue:PutSchemaVersionMetadata
          - glue:CreateSchema
          - glue:CreateRegistry
          Resource: 
          - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:registry/*"
          - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:schema/*/*"
      - VPCAccessPolicy: {}

Parameters:
  BootstrapServers:
    Type: String
    Description: Enter the bootstrap servers
    Default: CLUSTER_NAME
  KafkaTopic:
    Type: String
    Description: Enter the name of the Kafka Topic
    Default: KAFKA_TOPIC
  GlueSchemaRegistryName:
    Type: String
    Description: Enter the name of the Glue Schema Registry
    Default: GLUE_SCHEMA_REGISTRY_NAME
  ContactSchemaName:
    Type: String
    Description: Enter the name of the Contact Schema
    Default: AVRO_SCHEMA

Outputs:
  MSKConsumerLambdaFunction:
    Description: "Topic Consumer Lambda Function ARN"
    Value: !GetAtt LambdaKafkaConsumerJavaFunction.Arn
  KafkaProducerLambdaFunction:
    Description: "AVRO Producer Lambda Function ARN"
    Value: !GetAtt LambdaKafkaProducerJavaFunction.Arn
  ConsumerDLQUrl:
    Description: "URL of the Dead Letter Queue for the MSK Consumer"
    Value: !Ref ConsumerDLQ
  ConsumerDLQArn:
    Description: "ARN of the Dead Letter Queue for the MSK Consumer"
    Value: !GetAtt ConsumerDLQ.Arn
