/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.amazonaws.services.lambda.samples.events.kafka;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GlucoseReading extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1244094885891125843L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GlucoseReading\",\"namespace\":\"com.amazonaws.services.lambda.samples.events.kafka\",\"fields\":[{\"name\":\"device_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique identifier of the glucose monitoring device.\"},{\"name\":\"patient_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique identifier for the patient (pseudonymized or hashed).\"},{\"name\":\"glucose_mg_dL\",\"type\":\"int\",\"doc\":\"Glucose value in mg/dL.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GlucoseReading> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GlucoseReading> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GlucoseReading> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GlucoseReading> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GlucoseReading> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GlucoseReading to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GlucoseReading from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GlucoseReading instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GlucoseReading fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier of the glucose monitoring device. */
  private java.lang.String device_id;
  /** Unique identifier for the patient (pseudonymized or hashed). */
  private java.lang.String patient_id;
  /** Glucose value in mg/dL. */
  private int glucose_mg_dL;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GlucoseReading() {}

  /**
   * All-args constructor.
   * @param device_id Unique identifier of the glucose monitoring device.
   * @param patient_id Unique identifier for the patient (pseudonymized or hashed).
   * @param glucose_mg_dL Glucose value in mg/dL.
   */
  public GlucoseReading(java.lang.String device_id, java.lang.String patient_id, java.lang.Integer glucose_mg_dL) {
    this.device_id = device_id;
    this.patient_id = patient_id;
    this.glucose_mg_dL = glucose_mg_dL;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return device_id;
    case 1: return patient_id;
    case 2: return glucose_mg_dL;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: device_id = value$ != null ? value$.toString() : null; break;
    case 1: patient_id = value$ != null ? value$.toString() : null; break;
    case 2: glucose_mg_dL = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'device_id' field.
   * @return Unique identifier of the glucose monitoring device.
   */
  public java.lang.String getDeviceId() {
    return device_id;
  }


  /**
   * Sets the value of the 'device_id' field.
   * Unique identifier of the glucose monitoring device.
   * @param value the value to set.
   */
  public void setDeviceId(java.lang.String value) {
    this.device_id = value;
  }

  /**
   * Gets the value of the 'patient_id' field.
   * @return Unique identifier for the patient (pseudonymized or hashed).
   */
  public java.lang.String getPatientId() {
    return patient_id;
  }


  /**
   * Sets the value of the 'patient_id' field.
   * Unique identifier for the patient (pseudonymized or hashed).
   * @param value the value to set.
   */
  public void setPatientId(java.lang.String value) {
    this.patient_id = value;
  }

  /**
   * Gets the value of the 'glucose_mg_dL' field.
   * @return Glucose value in mg/dL.
   */
  public int getGlucoseMgDL() {
    return glucose_mg_dL;
  }


  /**
   * Sets the value of the 'glucose_mg_dL' field.
   * Glucose value in mg/dL.
   * @param value the value to set.
   */
  public void setGlucoseMgDL(int value) {
    this.glucose_mg_dL = value;
  }

  /**
   * Creates a new GlucoseReading RecordBuilder.
   * @return A new GlucoseReading RecordBuilder
   */
  public static com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder newBuilder() {
    return new com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder();
  }

  /**
   * Creates a new GlucoseReading RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GlucoseReading RecordBuilder
   */
  public static com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder newBuilder(com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder other) {
    if (other == null) {
      return new com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder();
    } else {
      return new com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder(other);
    }
  }

  /**
   * Creates a new GlucoseReading RecordBuilder by copying an existing GlucoseReading instance.
   * @param other The existing instance to copy.
   * @return A new GlucoseReading RecordBuilder
   */
  public static com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder newBuilder(com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading other) {
    if (other == null) {
      return new com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder();
    } else {
      return new com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder(other);
    }
  }

  /**
   * RecordBuilder for GlucoseReading instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GlucoseReading>
    implements org.apache.avro.data.RecordBuilder<GlucoseReading> {

    /** Unique identifier of the glucose monitoring device. */
    private java.lang.String device_id;
    /** Unique identifier for the patient (pseudonymized or hashed). */
    private java.lang.String patient_id;
    /** Glucose value in mg/dL. */
    private int glucose_mg_dL;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.device_id)) {
        this.device_id = data().deepCopy(fields()[0].schema(), other.device_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.patient_id)) {
        this.patient_id = data().deepCopy(fields()[1].schema(), other.patient_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.glucose_mg_dL)) {
        this.glucose_mg_dL = data().deepCopy(fields()[2].schema(), other.glucose_mg_dL);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing GlucoseReading instance
     * @param other The existing instance to copy.
     */
    private Builder(com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.device_id)) {
        this.device_id = data().deepCopy(fields()[0].schema(), other.device_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.patient_id)) {
        this.patient_id = data().deepCopy(fields()[1].schema(), other.patient_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.glucose_mg_dL)) {
        this.glucose_mg_dL = data().deepCopy(fields()[2].schema(), other.glucose_mg_dL);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'device_id' field.
      * Unique identifier of the glucose monitoring device.
      * @return The value.
      */
    public java.lang.String getDeviceId() {
      return device_id;
    }


    /**
      * Sets the value of the 'device_id' field.
      * Unique identifier of the glucose monitoring device.
      * @param value The value of 'device_id'.
      * @return This builder.
      */
    public com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder setDeviceId(java.lang.String value) {
      validate(fields()[0], value);
      this.device_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'device_id' field has been set.
      * Unique identifier of the glucose monitoring device.
      * @return True if the 'device_id' field has been set, false otherwise.
      */
    public boolean hasDeviceId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'device_id' field.
      * Unique identifier of the glucose monitoring device.
      * @return This builder.
      */
    public com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder clearDeviceId() {
      device_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'patient_id' field.
      * Unique identifier for the patient (pseudonymized or hashed).
      * @return The value.
      */
    public java.lang.String getPatientId() {
      return patient_id;
    }


    /**
      * Sets the value of the 'patient_id' field.
      * Unique identifier for the patient (pseudonymized or hashed).
      * @param value The value of 'patient_id'.
      * @return This builder.
      */
    public com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder setPatientId(java.lang.String value) {
      validate(fields()[1], value);
      this.patient_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'patient_id' field has been set.
      * Unique identifier for the patient (pseudonymized or hashed).
      * @return True if the 'patient_id' field has been set, false otherwise.
      */
    public boolean hasPatientId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'patient_id' field.
      * Unique identifier for the patient (pseudonymized or hashed).
      * @return This builder.
      */
    public com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder clearPatientId() {
      patient_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'glucose_mg_dL' field.
      * Glucose value in mg/dL.
      * @return The value.
      */
    public int getGlucoseMgDL() {
      return glucose_mg_dL;
    }


    /**
      * Sets the value of the 'glucose_mg_dL' field.
      * Glucose value in mg/dL.
      * @param value The value of 'glucose_mg_dL'.
      * @return This builder.
      */
    public com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder setGlucoseMgDL(int value) {
      validate(fields()[2], value);
      this.glucose_mg_dL = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'glucose_mg_dL' field has been set.
      * Glucose value in mg/dL.
      * @return True if the 'glucose_mg_dL' field has been set, false otherwise.
      */
    public boolean hasGlucoseMgDL() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'glucose_mg_dL' field.
      * Glucose value in mg/dL.
      * @return This builder.
      */
    public com.amazonaws.services.lambda.samples.events.kafka.GlucoseReading.Builder clearGlucoseMgDL() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GlucoseReading build() {
      try {
        GlucoseReading record = new GlucoseReading();
        record.device_id = fieldSetFlags()[0] ? this.device_id : (java.lang.String) defaultValue(fields()[0]);
        record.patient_id = fieldSetFlags()[1] ? this.patient_id : (java.lang.String) defaultValue(fields()[1]);
        record.glucose_mg_dL = fieldSetFlags()[2] ? this.glucose_mg_dL : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GlucoseReading>
    WRITER$ = (org.apache.avro.io.DatumWriter<GlucoseReading>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GlucoseReading>
    READER$ = (org.apache.avro.io.DatumReader<GlucoseReading>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.device_id);

    out.writeString(this.patient_id);

    out.writeInt(this.glucose_mg_dL);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.device_id = in.readString();

      this.patient_id = in.readString();

      this.glucose_mg_dL = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.device_id = in.readString();
          break;

        case 1:
          this.patient_id = in.readString();
          break;

        case 2:
          this.glucose_mg_dL = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










